### ISSUE TITLE
Ivy distribution??

### ISSUE THREAD

**Issue by JaimeBulaHNP** [alvarotrigo/angular-fullpage#101]
Think is time for an Ivy distribution.

**Comment by alvarotrigo** [comment]
Would you like to contribute to the project?
I'd be happy to compensate ;) 

Drop me a message [here](https://alvarotrigo.com/contact/) or [on twitter](https://twitter.com/imac2).

**Comment by ArjanKw** [comment]
For reference: there is now a PR #124 to make this possible.

**Comment by alvarotrigo** [comment]
Fixed in angular-fullpage v0.1.0! 🥳
