### ISSUE TITLE
How to autoplay horizontal slides

### ISSUE THREAD

**Issue by zeroseisdesign** [alvarotrigo/angular-fullpage#102]
I was trying with this: https://alvarotrigo.com/fullPage/help/how-to-autoplay-horizontal-slides-in-fullpage-js/
but Angular doesn't find the name 'fullpage_api' in this code adding in my component and can't compile:

`
// fullpage options
      licenseKey: 'MY_LICENSE',
      anchors: ['one', 'two'],
      navigation:false,
      slidesNavigation: true,
      verticalCentered:false,
      animateAnchor:false,
      autoScrolling:false,
      bigSectionsDestination:'top',
      fitToSection:false,
      paddingTop:69,
      controlArrows: false,
var g_interval: any;
     // for more details on config options please visit fullPage.js docs
this.config = {

afterLoad: function (origin: any, destination: any, direction: any) {
clearInterval(g_interval);

const lapse = 1000;

const shouldAutoPlay = destination.item.hasAttribute('data-auto');

const hasSlides = destination.item.querySelectorAll('.fp-slides').length;

if(shouldAutoPlay && hasSlides){
  g_interval = setInterval(function () {
//here is the bug
    fullpage_api.moveSlideRight();
  }, lapse);
}
},

};`
<img width="343" alt="image" src="https://user-images.githubusercontent.com/11144507/163943286-c164463d-0361-47ea-b9a3-902b2fac8043.png">

The const lapse seems to work, , but every second it shows this error:
TypeError: undefined is not an object (evaluating 'this.fullpage_api.moveSlideRight')

Any idea about configure this code to work in Angular?

Thanks in advance

**Comment by zeroseisdesign** [comment]
I have found the solution, now it works:

`afterLoad: (origin: any, destination: any, direction: any) => {
        clearInterval(g_interval);
    
        // 1000 milliseconds lapse
        const lapse = 3000;
        
        const shouldAutoPlay = destination.item.hasAttribute('data-auto');
    
        const hasSlides = destination.item.querySelectorAll('.fp-slides').length;
        
        if(shouldAutoPlay && hasSlides){
          g_interval = setInterval( () => {
            this.fullpage_api.moveSlideRight();
          }, lapse);
        }
      },`

**Comment by alvarotrigo** [comment]
Glad you did! :)
