### ISSUE TITLE
Translate anchors

### ISSUE THREAD

**Issue by zeroseisdesign** [alvarotrigo/angular-fullpage#103]
Hi, I'm working on a multilanguage website. Any tip on translating the anchors? I am using ngx-tranlate for the translations
Thanks in advance

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide any feature for that out of the box.

As long as you use the right language on the `data-anchor` attribute it should work as expected.

**Comment by zeroseisdesign** [comment]
ok, itt´s fine for me with data-anchor. thanks!
