### ISSUE TITLE
Navigation to fragment does not work

### ISSUE THREAD

**Issue by zeroseisdesign** [alvarotrigo/angular-fullpage#105]
Hi, I have changed the routing strategy in a project in angular to `HashLocationStrategy`, `useHash: true` in the app-`routing.module`. This adds the `#` symbol to the url, something like `mydomain.com/#/my-route`. Since I changed the strategy, due to a third party server incompatibility with `PathLocationStrategy`, anchor navigation has stopped working. Is there a fullpage.js configuration to fix this issue? Thanks in advance

**Comment by alvarotrigo** [comment]
> Is there a fullpage.js configuration to fix this issue? Thanks in advance

I don't think so.
How are URLs with fullpage.js anchors looking like? `mydomain.com/#/my-route#fullpage-anchor`?

You'd probably be better off by not using anchors in fullPage.js.
You can use the methods `moveTo` to scroll to the desired section/slide on click.
