### ISSUE TITLE
Issue with autoplay video

### ISSUE THREAD

**Issue by alvagabriel** [alvarotrigo/angular-fullpage#106]
I followed the fullpage demo to work with an angular app. A component with 3 sections and a video on the 2nd section. When I scroll to the second section the video is not playing even with autoplay settings, and I get this error on console:

- **Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.**

The only way to make it play is to click first on anything on the page and then scroll to the section with the video.

On the stackblitz demo it may seem to be working but if you open the application URL you can see the issue.

Demo on stackblitz: https://stackblitz.com/edit/angular-ivy-fg136l
Application URL: https://angular-ivy-fg136l.stackblitz.io

**Comment by alvarotrigo** [comment]
> The only way to make it play is to click first on anything on the page and then scroll to the section with the video.

I can't see any error in the console in my side and the video autoplay as expected.
What browser and OS are you using?

**Comment by alvagabriel** [comment]
Microsoft Edge, Version 101.0.1210.53 (Official build) (64-bit)

**Comment by alvagabriel** [comment]
I'm closing the issue. Apparently the problem was the angular framework and not fullpage js. I'm still not sure why but I had to get the video in the TS file and force the play event on ngOnInit.

**Comment by alvarotrigo** [comment]
Glad you managed to figure it out. And thanks for the info! ;)
