### ISSUE TITLE
.setAllowScrolling(false) not working

### ISSUE THREAD

**Issue by bogdanIuga** [alvarotrigo/angular-fullpage#108]
I'm trying to prevent scrolling in angular and it's not working... I do have a license, but deleted it for the photo

![image](https://user-images.githubusercontent.com/26706013/171505608-fa6d161f-cd65-4470-8a9c-2e4220982582.png)

**Comment by bogdanIuga** [comment]
![image](https://user-images.githubusercontent.com/26706013/171585387-b29cd955-a678-4134-82a6-8560efa26803.png)


not working

**Comment by bogdanIuga** [comment]
i've set on a button `this.fullpage_api.moveSectionDown()` and it's not working with the above config, but mouse scroll is enabled...

**Comment by alvarotrigo** [comment]
Can you provide a link to an isolated reproduction in codesandbox?
