### ISSUE TITLE
licenseKey error

### ISSUE THREAD

**Issue by devhardeep** [alvarotrigo/angular-fullpage#111]
We have purchased the license and added the key, but still getting the below error:

fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:

**Comment by devhardeep** [comment]
As our conversation, v4 is not compatible with Angular,. So, we are using now v3.

**Comment by alvarotrigo** [comment]
@ApostolosMavroukakis the OP closed it, not us :)

In any case, if you want to use fullPage.js version 3 you'll have to:

1- Get a **one-time payment** lifetime license from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>
2- Contact us using the [contact form](https://alvarotrigo.com/contact/) using the email used for the purchase and pointing out to this topic as a reference.
3- We'll then provide you a license for fullPage.js v3.

**Comment by ApostolosMavroukakis** [comment]
Thats exactly what i did thank you.
