### ISSUE TITLE
licenseKey requirement error

### ISSUE THREAD

**Issue by alvagabriel** [alvarotrigo/angular-fullpage#116]
Hi. We implemented the package as per the demo in the github readme but we are still getting the error "fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:". Are we missing something?

Here's a basic demo in stackblitz. I changed some letters from the license. but I can show you the mail with the full license if neccesary.
https://stackblitz.com/edit/fullpagejs-licensekey-error-4cfzwx?file=src%2Fapp%2Fapp.component.ts

**Comment by alvarotrigo** [comment]
Yeah, the Angular wrapper isn't updated and you probably purchased a v4 license.
Use the [contact form](https://alvarotrigo.com/contact/) and send us a message pointing to this issue.
