### ISSUE TITLE
@fullpage/angular-fullpage is not working on angular14

### ISSUE THREAD

**Issue by gylove1994** [alvarotrigo/angular-fullpage#120]
This likely means that the library (@fullpage/angular-fullpage) which declares AngularFullpageModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by gylove1994** [comment]
Dear Alvaro Trigo,

I am writing to request a refund for my purchase of "fullPage.js Commercial Hobby License (Lifetime)" from your store. Unfortunately, I have encountered an issue with the product that has rendered it unusable for my needs.

Specifically, I purchased "fullPage.js Commercial Hobby License (Lifetime)" with the intention of using the fullPage.js library in an Angular application. However, I have discovered that this library is unable to receive updates within the Angular environment, which means that I am unable to make necessary changes or improvements to my website.

As a result, I believe that the product is not fit for its intended purpose and does not meet my expectations. Therefore, I am requesting a full refund of the purchase price.

I understand that your store has a refund policy in place, and I would appreciate it if you could process my refund as soon as possible. Please let me know if there is any further information I can provide to facilitate this process.

Thank you for your attention to this matter.

Sincerely,

YanGeng

**Comment by gylove1994** [comment]
Dear @alvarotrigo ,

I am writing to inquire about the possibility of providing maintenance services for the Angular version of fullPage.js. While I have encountered issues with the library's compatibility with Angular, I am willing to work with you to ensure that the product is functioning as intended.

If you are interested in exploring this option, I would be happy to provide my expertise in the Angular environment. I believe that this could be a mutually beneficial arrangement, as it would allow me to continue using the product while providing you with valuable feedback and support.

In exchange for my services, I would like to request a professional license for fullPage.js and all associated paid plugins upon successful completion of the maintenance work. I understand that this is a significant request, but I believe that it is a fair exchange for my time and expertise.

Please let me know if you are interested in pursuing this option or if you require any additional information from me.

Thank you for your attention to this matter.

Sincerely,

YanGeng

**Comment by alvarotrigo** [comment]
@gylove1994 sure no problem!
Please contact us using the [contact form](https://alvarotrigo.com/contact/) using the email you used for the purchase.
Make sure to link to this issue or explain the situation again and we'll refund you.
