### ISSUE TITLE
Fullpage is not working with Angular 16.2

### ISSUE THREAD

**Issue by zeroseisdesign** [alvarotrigo/angular-fullpage#121]
Hi,

After install full page-angular and configure it, this is the error generated:
'AngularFullpageModule' does not appear to be an NgModule class.(-996002)
angular-fullpage.module.d.ts(1, 22): This likely means that the library (@fullpage/angular-fullpage) which declares AngularFullpageModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
(alias) class AngularFullpageModule
import AngularFullpageModule

Is there any solution or configuration changes so that there is no error or perhaps it isn´t compatible with the latest version of angular?

Thanks in advance

**Comment by alvarotrigo** [comment]
I guess it's not yet compatible with Ivy, there's another open issue about it [here](https://github.com/alvarotrigo/angular-fullpage/issues/101).

> perhaps it isn´t compatible with the latest version of angular?

That's correct. It is not yet compatible with the latest version.
There's another issue on this [here](https://github.com/alvarotrigo/angular-fullpage/issues/75).

**Comment by ArjanKw** [comment]
For reference: there is now a PR #124 to make this possible. I now have a working Angular 16 site, with FullPage v4.

To make it work using the PR (before the PR is merged), you can add this to your dependencies:

`"@fullpage/angular-fullpage": "https://github.com/alidihaw/angular-fullpage#dev",`
