### ISSUE TITLE
2 vulnerabilities (1 moderate, 1 high)

### ISSUE THREAD

**Issue by urban-hostel** [alvarotrigo/angular-fullpage#122]
added 3 packages, and audited 1168 packages in 4s

114 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 moderate, 1 high)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

# npm audit report

fullpage.js  <=4.0.4
Severity: high
Cross-site Scripting in fullpage.js - https://github.com/advisories/GHSA-h3cq-j957-vhxg
Prototype Pollution in fullpage.js - https://github.com/advisories/GHSA-vpgw-ffh3-648h
No fix available
node_modules/@fullpage/angular-fullpage/node_modules/fullpage.js
  @fullpage/angular-fullpage  *
  Depends on vulnerable versions of fullpage.js
  node_modules/@fullpage/angular-fullpage

2 vulnerabilities (1 moderate, 1 high)

Some issues need review, and may require choosing
a different dependency.

**Comment by alvarotrigo** [comment]
Yeap, the Angular wrapper needs an update to work with fullPage.js version 4.
The vulnerability probably won't exist there.

Duplicated of https://github.com/alvarotrigo/angular-fullpage/issues/75
