### ISSUE TITLE
fullPage.js types improved

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/angular-fullpage#14]
@vh13294 could you double check [my commit regarding the fullpage.js types](https://github.com/alvarotrigo/angular-fullpage/commit/2b46b8281e508687531c5e2b2465c8e9ff522b61)?

Not quite sure why some callbacks were set as `any` and others as `void`.
So correct me if I need to revert some changes.

Notice I'm commiting now to the `dev` branch. 
I'll merge all improvements to the branch in each new release.

**Comment by vh13294** [comment]
The types are not being used at the moment.

Anyway to answer your question, I don't think there is a type :function for variable.

Usually for callback function, we define it like:

Some_callback?(flag?: any) : boolean;
Some_callback?(flag?: any) : void; // no return
Some_callback?() : void; // no return, no input

**Comment by vh13294** [comment]
I've made an improvement on type defintions here

https://github.com/alvarotrigo/angular-fullpage/commit/8bb9c003dacbae61b07125555cbd9a4a1120db00

**Comment by alvarotrigo** [comment]
@vh13294 awesome! Thanks!

**Comment by alvarotrigo** [comment]
@koswarabilly are you using the latest version 0.0.8 ?
If so, can you please provide an isolated reproduction of your issue in codesandbox or [Stackblitz](https://stackblitz.com/edit/angular-nqsqwk)

**Comment by vh13294** [comment]
-you might have to install fullpage.js manually.
=> as it is a peer-dependency.

But it will be fixed in the next release!

https://github.com/alvarotrigo/angular-fullpage/commit/ac93efce7088f4b660d6f6c431e22776b4b5e310

**Comment by alvarotrigo** [comment]
@vh13294 uh! Well spotted!

**Comment by alvarotrigo** [comment]
@koswarabilly try now with the new release 0.0.9

**Comment by koswarabilly** [comment]
It works now. But it seems like `@import url(~fullpage.js/dist/fullpage.min.css);` is not found yet. is it because i use css instead of scss?

**Comment by koswarabilly** [comment]
I see that the slide does not work..

**Comment by vh13294** [comment]
not sure about the css syntax.

But could you try this instead?

@import '~fullpage.js/dist/fullpage.min.css';

**Comment by koswarabilly** [comment]
Oh stupid me! thank you for the information. 
I suggest to add this to your documentation for user that does not use scss as their default style.
