### ISSUE TITLE
Add npm script to build the project?

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/angular-fullpage#19]
Should we add a new npm script to build the project and generate the dist files?

```shell
npm run build angular-fullpage
```

Right now we have the following ones:
```js
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
```

**Comment by vh13294** [comment]
"npm run build angular-fullpage" is for building the library.

"npm run build" is for building the examples.

Both generate their own dist folders.

**Comment by alvarotrigo** [comment]
Yeah, I was just wondering if we should have something like this then:

```js
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build angular-fullpage",
    "build:example": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
```

**Comment by vh13294** [comment]
yeah, 
I think that is a good idea, I'll take a look.

**Comment by alvarotrigo** [comment]
Thanks for that!
