### ISSUE TITLE
Update Stackblitz

### ISSUE THREAD

**Issue by vh13294** [alvarotrigo/angular-fullpage#23]
Should we update the Stackblitz to match the lastest update?

**Comment by alvarotrigo** [comment]
True! Thanks for the reminder!

I've updated it now: 
I removed the fullPage.js dependency and bumped the angular-fullpage package to 0.0.9.

However, I'm having troubles with importing the fullpage CSS file in styles.css:
<img width="610" alt="screen shot 2018-12-05 at 11 50 04" src="https://user-images.githubusercontent.com/1706326/49509675-4fa01f00-f886-11e8-9ba8-8f5a9fb3afaa.png">

Any idea what can be the cause?

**Comment by alvarotrigo** [comment]
It seems it only works when I add fullpage.js as a dependency instead of relaying in the angular-fullpage dependencies.

**Comment by vh13294** [comment]
I gave it a try again, and it works now without fullpage.js dependency!

Weird!

**Comment by alvarotrigo** [comment]
Uh! True!
No idea what happened :D 

I'll close the issue then!

**Comment by alvarotrigo** [comment]
Ok, now it doesn't work again?

**Comment by vh13294** [comment]
Yeah, we might need to put the fullpage.js dependency back in.

Last time , I removed it and still work probably due to npm cached. I think !

**Comment by alvarotrigo** [comment]
I added it back.
