### ISSUE TITLE
SSR not working properly

### ISSUE THREAD

**Issue by davidstellini** [alvarotrigo/angular-fullpage#24]
The library is trying to import `fullpage.js/dist/fullpage.extensions.min'`, no matter if it's running on platform browser or server. The fullpage extensions file in turn tries to do funny things with `window`, which breaks SSR rendering. I can open a PR, I think it should be a quick fix.

**Comment by vh13294** [comment]
I don't have much experience with angular-universal.
Shouldn't it be fixed by using Server-side DOM such as domino in your server.js?

If you can open a PR, that would be great!

**Comment by alvarotrigo** [comment]
> The fullpage extensions file in turn tries to do funny things with `window`, which breaks SSR rendering.

fullpage.js relies on the window object for many things, as you can see on the [sourcecode](https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js), but if you think you can find a solution for this issue please feel free to open a PR.

**Comment by davidstellini** [comment]
Sure. I don't know if you'll like it but the solution I found to work is not to import fullpage.js in the first place if it's running under server side code. I see there's already isPlatformBrowser checks to make sure it's not initialized, but it seems fullpage.js is using window as soon as it's required, not initialized, so the checks aren't really helping. I got it to work - I'll open a PR soon.

**Comment by davidstellini** [comment]
https://github.com/alvarotrigo/angular-fullpage/pull/25

**Comment by davidstellini** [comment]
> > The fullpage extensions file in turn tries to do funny things with `window`, which breaks SSR rendering.
> 
> fullpage.js relies on the window object for many things, as you can see on the [sourcecode](https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js), but if you think you can find a solution for this issue please feel free to open a PR.

Also the same check can be possibly added in the fullpage library

**Comment by davidstellini** [comment]
> I don't have much experience with angular-universal.
> Shouldn't it be fixed by using Server-side DOM such as domino in your server.js?
> 
> If you can open a PR, that would be great!

For some reason it still seems to fail even when domino is being used. I can maybe replicate it on a fork of this repo, which is also using domino in the server.ts: https://github.com/Angular-RU/angular-universal-starter/blob/master/server.ts
I'm not sure why, I'm not very experienced with angular universal either, but adding in domino was one of the first things I tried.

**Comment by vh13294** [comment]
`
global['window'] = win;
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true,
    };
  },
});
global['document'] = win.document;
global['CSS'] = null;
// global['XMLHttpRequest'] = require('xmlhttprequest').XMLHttpRequest;
global['Prism'] = null;
global['DOMTokenList'] = win.DOMTokenList;
global['Node'] = win.Node;
global['NodeList'] = win.NodeList;
global['Text'] = win.Text;
global['HTMLElement'] = win.HTMLElement;
global['navigator'] = win.navigator;
`
these are the list of variables that you have to declare!
Try this first to if it work.

**Comment by davidstellini** [comment]
Hi. First of all thank you for your reply and your time - and apologise for the long time taken to reply. I tried the above code on the server side - unfortunately I couldn't get it to work with the same error as before.

Also, defining the window object makes many libraries think that they are working in the browser if they use these checks:
`typeof window !== 'undefined'`
This can make other libraries behave erratically. I have managed to avoid it so far, and ideally, would really like to keep it this way.

I have pointed the project using @angular/fullpage to this commit: https://github.com/alvarotrigo/angular-fullpage/pull/25/commits/5c6c4b09897f44896dcc72ba2a1fe4d5cd4c7bf0
And it has been working like a charm since January. Do you have any other workaround in mind or would you be able to add the check to this library to give it SSR support?

Again, thank you so much for your time!

**Comment by alvarotrigo** [comment]
@vh13294 any thoughts on that PR?

**Comment by davidstellini** [comment]
Thanks for your quick reply - look forward to resolving this issue

**Comment by vh13294** [comment]
@alvarotrigo it's not the most elegant solution. But it's a good support for SSR.

**Comment by alvarotrigo** [comment]
@vh13294 should we merge it ?

@davidstellini I can not see your PR [in this repository](https://github.com/alvarotrigo/angular-fullpage/pulls). Can you please create it here so we can merge it?
Otherwise we will just make the changes by ourselves.

**Comment by davidstellini** [comment]
If you can, as I'm abroad without access to my laptop for a few days.
Otherwise I'll open another PR in a few days.

**Comment by vh13294** [comment]
@alvarotrigo  I will try to find a proper solution.

@davidstellini 

Is it possible to check for platform-server or browser at your end? Then do this

```javascript
"window is not defined" came from 3rd party library which accessing window variable.

You should wrapping your code with browser check condition

In html,

<ng-container *ngIf="isBrowser">
   <!-- In my case, ngx-siema & ngx-slcik -->
   <ngx-siema></ngx-siema> 
</ng-container>
In ts,

isBrowser;
constructor(@Inject(PLATFORM_ID) private platformId) { 
   this.isBrowser = isPlatformBrowser(platformId);
}

...

if (this.isBrowser) { 
  // put your code which is access window variable 
} 
```

**Comment by davidstellini** [comment]
Hi @vh13294 - I have these checks all over the app;
```
if (this.isBrowser) { 
  // put your code which is access window variable 
} 
```

The issue is that:
1. As soon as if the `AngularFullpageModule` is imported in a module;
2. This line is executed straight away: ` import fullpage from 'fullpage.js/dist/fullpage.extensions.min';`
3. The fullpage extensions tries to access the window variable. So the `this.isBrowser` check should either be in the place that is accessing the window variable (fullpage extensions, which seems to not be possible) - or we can stop the chain that causes the issue somewhere before.

Anyone who uses your library with SSR, will have their app break as soon as they import your module from the server side. 

What I have tried to do is not import the module in the first place, but it's tricky.

**Comment by vh13294** [comment]
@alvarotrigo  This is how react-fullpage solves the SSR issue, 

https://github.com/alvarotrigo/react-fullpage/blob/5a11fb5211e5706da81f2874516f023dc6e5aa88/components/index.js#L17

It's similar, but more refined. I think it's okay to merge.

**Comment by alvarotrigo** [comment]
@vh13294 thanks for the info!
Could you please confirm the commit I just made should solve this issue? https://github.com/alvarotrigo/angular-fullpage/commit/edc8953b8d8b96dc7f806f03658fe9cd60e192f4

I'll then create a new version, merge it and publish it to npm.

**Comment by alidihaw** [comment]
the latest version not have import fullpage.js/dist/fullpage.extensions.min.js on directive
the import its already on import angular.json

and also we already have check for ssr or no on directive
```
ngAfterViewInit() {
  if (isPlatformBrowser(this.platformId)) {
    this.initFullpage();
  }
  if (isPlatformServer(this.platformId)) {
    // server side code
  }
}
```

**Comment by alvarotrigo** [comment]
@alidihaw, thanks for clarifying it! 👍
