### ISSUE TITLE
scrollOverflow is not working

### ISSUE THREAD

**Issue by wiadev** [alvarotrigo/angular-fullpage#26]
Hi
I've included scrolloverflow.min.js and set the following flags in config.
```
scrollOverflow: true,
scrollOverflowReset:true,
```

But scrollOverflow is still not working.

![screenshot at jan 14 08-56-03](https://user-images.githubusercontent.com/18234060/51127471-5baec300-17da-11e9-92df-d5e2206f3c82.png)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by wiadev** [comment]
https://codepen.io/wiadev/pen/pqGyPZ

Sorry, my question was for `scrollOverflowReset:true`

Do I need to purchase an extension and include an additional script to make it work?

**Comment by alvarotrigo** [comment]
> Do I need to purchase an extension and include an additional script to make it work?

Yeap, you'll need to acquire them first from the [fullpage.js extensions](https://alvarotrigo.com/fullPage/extensions/) page.
