### ISSUE TITLE
Issues with dynamic changes in offset section

### ISSUE THREAD

**Issue by mathiasritter** [alvarotrigo/angular-fullpage#31]
Hi,

I am using angular fullpage with the offset sections plugin and I have two issues with adding content dynamically to an offset section.

After adding content to the section, I call `fullpage_api.build();` as described in the readme. The first problem is that the scroll position jumps to the top of the section when calling this method.

After adding content multiple times to the section, I encountered another problem: When navigating to the section, fullpage does not scroll to the selected section. This issue gets bigger as I add more and more content to the section.

Here is a screen recording: https://cl.ly/a7a91e8ff63b
I've reproduced the issues here: https://stackblitz.com/edit/angular-fullpage-issues

**Comment by vh13294** [comment]
I see you use *ngFor inside the directive. 
Sorry for the confusion, dynamic build in this case refer to when you manually manipulate the Dom.

For the use of *ngFor please see:
https://github.com/alvarotrigo/angular-fullpage/blob/master/demo/app/examples/dynamic-ng-for/dynamic-ng-for.component.ts#L45

You have to detect dom ready then you can call rebuild just like in the example.

**Comment by mathiasritter** [comment]
Thanks for the quick response. I changed my code as shown in the example and the navigation problem seems to be fixed.

However, I still have the problem that the scroll position jumps to the top of the section after clicking the button to load more elements. Is this the intended behaviour?

**Comment by vh13294** [comment]
the reference should be in the same line as the *ngFor.

Regarding the question, could you explain more what you're trying to acheive?

Techically, this is a fullpage application if you want some add extra stuff to one section, have you tried looking into scroll inside section?

example:
https://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage

**Comment by mathiasritter** [comment]
What I want to achieve is a portfolio section with posts, with a button to load more posts from the backend. This portfolio section is an offset section data-height 0 so that the height of it is adjusted to the number of posts loaded. Also, autoscrolling is disabled for all sections. You can see a demo here: http://angular.austriandominoart.com/#portfolio

**Comment by alvarotrigo** [comment]
Try without using the offset section.
If you still have issues, then please create an issue on the fullPage.js repository and provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Oh I forgot to say, try without angular-fullpage.js too to see if the issue is in fullPage.js, in Angular-fullpage.js or in the offset extension.

**Comment by mathiasritter** [comment]
@alvarotrigo When I don't use offset sections the issues do not occur. They only occur when the extension is enabled. I've created two isolated reproductions. One with fullpage.js only and one with the angular wrapper.

In the fullpage.js reproduction, the scroll position stays the same after clicking the button to load more content into the section. However, the other problem that the navigation link scrolls to the wrong position is still present: https://jsfiddle.net/mathiasritter/4skerzLh/28/

As for the angular fullpage reproduction, it's the same two problems that I initially described. In addition to the problem that pure fullpage.js reproduction has, the scroll position jumps to the top of the section after clicking the button: https://stackblitz.com/edit/angular-fullpage-issues

@vh13294 I looked at the "scroll inside section" feature. However, I cannot use it because I have set `autoScrolling: false` and those two features do not work together.

**Comment by alvarotrigo** [comment]
It happens without the extension as well. 
See the reproduction by using fp-auto-height in here:
https://jsfiddle.net/alvarotrigo/6jxq8crz/2/

> Should I also create an issue on the fullPage.js repository?

Yeah please. This is no longer an angular-fullpage issue and neither an extension one.

**Comment by mathiasritter** [comment]
@alvarotrigo I looked at your reproduction. After loading some content, the navigation link to section 3 scrolls to the correct position - which is not the case in my reproduction (with the offset sections)?

**Comment by alvarotrigo** [comment]
@mathiasritter just make sure to remove the attribute `data-percentage` when adding content to the section:

https://jsfiddle.net/alvarotrigo/2qvt6rwa/2/

**Comment by mathiasritter** [comment]
Thanks, I will create an issue later
