### ISSUE TITLE
Angular 6 routing conflict

### ISSUE THREAD

**Issue by tridentmakarov** [alvarotrigo/angular-fullpage#32]
### Angular Routing causes issue with scrolling on FullPage.js

These are the fullpage options used: 

		anchors: ['firstPage', 'secondPage', 'thirdPage', 'fourthPage', 'lastPage'],
		sectionsColor: ['#7BAABE', 'whitesmoke', '#7BAABE', 'whitesmoke', '#7BAABE'],
		menu: '#menu',
		lockAnchors: true,

Testing by moving the fullpage code outside of the router proves that the router is what causes the issue with FullPage, where it creates a scrollbar and allows the user to scroll midway between two sections.

All code tested with was the original code from https://www.npmjs.com/package/@fullpage/angular-fullpage, placed inside of a router.

### Steps to reproduce it
1. Angular Routing, setup child page that uses fullpage. 
2. Navigate to child, and scroll a relatively significant amount.
3. Section will move beyond its area, showing the next section
### Versions 
Chrome and Firefox, Angular 6, latest fullpage.js
This is an example of what is seen when scrolling, the two colors are from two sections.

<img width="955" alt="Screen Shot 2019-03-15 at 10 04 19 AM" src="https://user-images.githubusercontent.com/3821507/54438383-f1000200-470c-11e9-805a-c7a0c7d3745c.png">

**Comment by alvarotrigo** [comment]
I'm transferring the issue to the right repository.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction of the issue in Stackblitz, Codesandbox or any similar one?
Use the less amount of HTML code and no external CSS or JS to fullpage.js.

**Comment by tridentmakarov** [comment]
Actually, I've narrowed it down to mat-sidenav-container, where when I use it the scrolling occurs. Instead, I got rid of the sidenav entirely and solved the issue.
