### ISSUE TITLE
Destroy and init FullpageJS in angular

### ISSUE THREAD

**Issue by htruong24** [alvarotrigo/angular-fullpage#34]
Hi team, 

I see many example how to destroy and init fullpageJS using Javascript, but how could I destroy and then init again in angular. For example in getRef function I've defined like this:

getRef(fullPageRef) {
    this.fullpage_api = fullPageRef;
    this.fullpage_api.destroy('all');
// How could I init the fullpage again?
  }

So after destory the fullpagejs, how could I init it again in angular?

**Comment by vh13294** [comment]
this method 
```javascript
this.fullpage_api.build();
```
will do just that.

**Comment by htruong24** [comment]
It doesn't work.

**Comment by alvarotrigo** [comment]
What build does is destroy and initialise fullpage.js straight away. 

Perhaps you want to only destroy it first, and then, after some action, initialise it again?

**Comment by htruong24** [comment]
For now I have a main page and a pop up both use FullPageJS.
Main page: I have 5 sections
In popup page I have 3 sections.

So if i'm now in the main page and then click a button to show the popup page, the number of page in popup still be calculated to 5. 

So in the popup I need to destory and init the fullpage for it.

**Comment by alvarotrigo** [comment]
@vh13294 might be able to answer you better.
But an isolated reproduction of the issue in [stackblitz](https://stackblitz.com/edit/angular-nqsqwk) or codesandbox would definitely help to get a faster answer for you.

**Comment by htruong24** [comment]
@alvarotrigo yes, just update this function from your stackbliz, I think it is enough.

getRef(fullPageRef) {
this.fullpage_api = fullPageRef;
**this.fullpage_api.destroy('all'); // Destroy the full page first
this.fullpage_api.buid(); // Init it again => Not working**
}

**Comment by vh13294** [comment]
try seperate the #id of the two fullpage elements

this.fullpage_api_1
this.fullpage_api_2

when the popup is opened, destroy the first and build the second.

**Comment by htruong24** [comment]
Hi @vh13294, @alvarotrigo 

Thanks for your support. The first solution is worked but I still got the issue like this:

When I open the popup, I will destroy the first page by using this function: this.fullpage_api_1.destroy('all'); then open the popup => it worked. 

But then if I close this popup I need to init the fullpage_api_1  for the main page again, and if I use this.fullpage_api_1.build();  or  this.fullpage_api_1. reBuild();  it still doesn't work.

The issue is basically the same I asked before, how could we reinit the fullpage_api after destroy it using this function this.fullpage_api_1.destroy('all'); 

The second solution doesn't work, got the same issue like before.

Thanks

**Comment by htruong24** [comment]
Could we do something the same like we define in directive to init a new full page instead of using directive?
  this.fullpage_api = new fullpage('#' + this.id, this.options);

**Comment by vh13294** [comment]
You could try it in pure JavaScript(vanilla) first and see if you can achieve that.

And also you might want to look into this
https://github.com/alvarotrigo/fullPage.js/issues/1029
