### ISSUE TITLE
FullPageJs with static header

### ISSUE THREAD

**Issue by htruong24** [alvarotrigo/angular-fullpage#35]
Hi team, 
 
My page currently have a static header with height is 110px. I'm now using property paddingTop : '110px' but seam like it work incorrectly.

It will create a padding-top: 110px for each section so the height of fb-table is not correct and the scrolling position is the same.

**Comment by alvarotrigo** [comment]
Try using a container in the section and setting the margin or padding to it instead:

```html
<div class="section">
   <div class="my-content">
        Contet here
   </div>
</div>
```

If you still have issues, then please create an issue on the fullpage.js repository (not this one) with an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by htruong24** [comment]
Hi @alvarotrigo,

Please help check this: https://jsfiddle.net/Hieu_Truong/9awxv1gm/

**Comment by alvarotrigo** [comment]
Your answer:
https://jsfiddle.net/alvarotrigo/6qazLsrt/1/
