### ISSUE TITLE
FullPageJs with static header

### ISSUE THREAD

**Issue by htruong24** [alvarotrigo/angular-fullpage#36]
Hi @alvarotrigo,

Please help check this: https://jsfiddle.net/Hieu_Truong/9awxv1gm/

**Comment by alvarotrigo** [comment]
1- This is not the right repository to report a fullpage.js question/issue
2- This is not fullpage.js related but about basic CSS knowledge.

3. Here's your answer, just use the appropriate CSS style for the fixed header.
https://jsfiddle.net/alvarotrigo/y2or8mah/
