### ISSUE TITLE
Not working in angular 8, I can't install it

### ISSUE THREAD

**Issue by jlrc23** [alvarotrigo/angular-fullpage#43]
When  i tried install:

`npm WARN @fullpage/angular-fullpage@0.0.12 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fullpage/angular-fullpage@0.0.12 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`

`npm ERR! path C:\Users\rojo7006\practicas\lor\lorval2019\node_modules\@types\jasmine\ts3.1
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\rojo7006\practicas\lor\lorval2019\node_modules\@types\jasmine\ts3.1'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Users\rojo7006\practicas\lor\lorval2019\node_modules\@types\jasmine\ts3.1']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\rojo7006\practicas\lor\lorval2019\node_modules\@types\jasmine\ts3.1'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\Users\\rojo7006\\practicas\\lor\\lorval2019\\node_modules\\@types\\jasmine\\ts3.1' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\Users\\rojo7006\\practicas\\lor\\lorval2019\\node_modules\\@types\\jasmine\\ts3.1\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\Users\\rojo7006\\practicas\\lor\\lorval2019\\node_modules\\@types\\jasmine\\ts3.1',
npm ERR!   parent: 'lorval2019' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).`

**Comment by alvarotrigo** [comment]
@vh13294 any tips for this guy?

**Comment by alvarotrigo** [comment]
@jlrc23 how are you trying to install it?

**Comment by vh13294** [comment]
@jlrc23  @vh13294  it seems like something to do with the window permission in drive C:

**Comment by alvarotrigo** [comment]
@vh13294 thanks for the info!! 👍
