### ISSUE TITLE
When I use variable in href, href will disappear.

### ISSUE THREAD

**Issue by edward24689** [alvarotrigo/angular-fullpage#50]
Code:
`<a data-fancybox [href]="item">
</a>
`
Result:
`<a _ngcontent-oxd-c13=""  ng-reflect-href="http://mydomain.com/"></a>`

**Comment by vh13294** [comment]
That is an issue with angular not fullpage.js

Please see here

https://keenthemes.com/forums/topic/href-auto-replaced-by-ng-reflect-href-problem/

**Comment by alvarotrigo** [comment]
@vh13294 thanks for the quick answer! ;)

**Comment by felipefanucchi** [comment]
I'm having the same problem here, the link you attached is broken.
How the problem can be with angular if it only happens after I activate the plugin?
Thank you!

**Comment by alvarotrigo** [comment]
@vh13294 any insights ?

**Comment by vh13294** [comment]
Please read the angular document.

You can use 

<a [attr.href]="..."></a>

Or

<a href="{{your expression here}}"></a>

https://stackoverflow.com/a/45509126

**Comment by felipefanucchi** [comment]
I've tried before the {{}} and also didn't work. 
But I forgot of the [attr.*], it worked fine.

Thanks for the answer.

Following an example for those who are having the same problem.

![image](https://user-images.githubusercontent.com/15599005/71544426-01acfc00-295e-11ea-9c5e-7ca8c26612fb.png)

![image](https://user-images.githubusercontent.com/15599005/71544430-0c679100-295e-11ea-9478-4dd36c6f001c.png)
