### ISSUE TITLE
Angular 8 incompatibility

### ISSUE THREAD

**Issue by adver89** [alvarotrigo/angular-fullpage#52]
I got error when I'm trying do Angular update:

> Package "@fullpage/angular-fullpage" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.2.4").
>                   Package "@fullpage/angular-fullpage" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.2.4").
> Incompatible peer dependencies found. See above.
>

**Comment by vh13294** [comment]
You could try:

`ng update @angular/core --force`

https://stackoverflow.com/questions/50508334/when-upgrading-angular-5-to-6-i-get-incompatible-peer-dependency-using-ng-upda

**Comment by adver89** [comment]
As first comment in top answer says:

> using force is usually not recommended
I would force update, but maybe angular-fullpage is compatible with Angular 6 from some reason.

**Comment by vh13294** [comment]
It is compatible with any version of Angular > 2. 

So that should be fine you can ignore the warning.

**Comment by adver89** [comment]
Thanks @vh13294
