### ISSUE TITLE
moveTo(a, b) does not work properly

### ISSUE THREAD

**Issue by GianniAzizi** [alvarotrigo/angular-fullpage#55]
Hello,

The moveTo(a, b) function does not work properly. 
The scroll to the section works correctly but the slide does not move.

Example : 

```html
<div class="section">
    <div class="slide">slide1</div>
    <div class="slide">slide2</div>
    <div class="slide">slide3</div>
</div>
<div class="section>
</div>
```

```js
fullpage_api.moveTo(1,1)
```

Thank you in advance.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [stackblitz](https://stackblitz.com/edit/angular-nqsqwk) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
