### ISSUE TITLE
Height issue on first load

### ISSUE THREAD

**Issue by binoopmj** [alvarotrigo/angular-fullpage#56]
On first load all sections have height issues. 80px height of the next slide is visible in current viewport.

**Comment by alvarotrigo** [comment]
I can't reproduce your issue on [this demo](https://stackblitz.com/edit/angular-nqsqwk) or on the [main website](https://alvarotrigo.com/angular-fullpage/) for that matter.

Can you please provide an isolated reproduction in [stackblitz](https://stackblitz.com/edit/angular-nqsqwk) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by binoopmj** [comment]
@alvarotrigo I could find out the solution. It was a style appending to my <html> tag, which produce issue in scrolling.
