### ISSUE TITLE
Can't click on the slides right arrow

### ISSUE THREAD

**Issue by wadie** [alvarotrigo/angular-fullpage#57]
The dots on the right side for scrolling hide the right arrow element for the slides which makes it difficult to click.

See screenshot
![image](https://user-images.githubusercontent.com/1206307/70990529-07852080-20c6-11ea-9dea-f38d39364208.png)

**Comment by alvarotrigo** [comment]
Yeap, that's just because of the fullpage navigation is on top of the arrow.

Just overwrite the CSS of any, the bullet navigation or the arrows, to place them a bit further from each other, or avoid using navigation when  using the arrows. 

You choose :)
