### ISSUE TITLE
scrollOverflow doesn't work

### ISSUE THREAD

**Issue by csimpi** [alvarotrigo/angular-fullpage#59]
Hi,
I'm using Angular 8.
I've installed angular-fullpage with npm, and purchased a Hobby license of fullpageJS, the license code has been added to the config object.

I've copy-pasted your scrollOverflow example, added the js file to the angular.json file to the scripts section, I'm still getting:

`fullPage: The option scrollOverflow:true requires the file scrolloverflow.min.js. Please include it before fullPage.js.` error message in the JS console. Why?

When I open the source code of the HTML page in the browser I can find the scrollOverflow js content in the `srcipts.js` file.

**Comment by alvarotrigo** [comment]
The [scrollOverflow demo](https://github.com/alvarotrigo/angular-fullpage/tree/master/demo/app/examples/scrolloverflow) is working perfectly for me.

There's also an explanation about it in the docs regarding how to use scrollOverflow:
https://github.com/alvarotrigo/angular-fullpage#use-of-scrolloverflow

If you stitll having issues, please create an isolated reproduction in codesandbox or [stackblitz](https://stackblitz.com/edit/angular-nqsqwk)

**Comment by csimpi** [comment]
@alvarotrigo I don't have time to create a stackblitz, but I'm still getting the same error if I follow the example's instructions.
The only way to make it work if I place ` <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.8/vendors/scrolloverflow.min.js"></script>`

in the `header` tag of my Angular project's main template file (index.html)

**Comment by OsamaYousry** [comment]
I reproduced the issue on this stackblitz. Please let me know what to do to fix it.
https://stackblitz.com/edit/angular-csswxo

**Comment by alvarotrigo** [comment]
@OsamaYousry  you are not loading the right package for fullpage.js and not even loading the styles. It should be `fullpage.js`, version 3.0.8 is the latest. 

Regarding scrollOVerflow, it seems Stackblitz is not loading it for some reason, not sure why. Howerver you can test the example for scrollOverflow provided in the project, it works as expected:
https://github.com/alvarotrigo/angular-fullpage/tree/master/demo/app/examples/scrolloverflow

**Comment by OsamaYousry** [comment]
I followed these steps:
-npm install @fullpage/angular-fullpage
-I imported the css in the styles file (but forgot to do it in the stackblitz)
And still the same issue occurs on my environment. 
I copied the code from the example to the stackblitz to be able to reproduce it and it's happenning on it.

Also here's screenshots from my package.json
![image](https://user-images.githubusercontent.com/13081893/83079180-8f128a80-a07b-11ea-9d61-deb170cb22bc.png)

My style.scss

![image](https://user-images.githubusercontent.com/13081893/83079203-9df93d00-a07b-11ea-99b1-5f1907fb07bd.png)

My angular.json
![image](https://user-images.githubusercontent.com/13081893/83079234-aea9b300-a07b-11ea-91f0-900a48a40d5e.png)

The only thing that made it work is following @csimpi's advice to do this:

> The only way to make it work if I place <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.8/vendors/scrolloverflow.min.js"</script> in the header tag of my Angular project's main template file (index.html)

Which I don't think is good practice in Angular

**Comment by alvarotrigo** [comment]
@OsamaYousry yeah it seems the scripts part in angular.json is not taking effec on stackbliz.
However it all works as expected on the example provided on the project.

You can test it yourself by following the readme instructions on the demo folder:
https://github.com/alvarotrigo/angular-fullpage/tree/master/demo#examples
