### ISSUE TITLE
Move examples in the demo to stackblitz

### ISSUE THREAD

**Issue by gabrielstellini** [alvarotrigo/angular-fullpage#60]
As things stand, this project has an examples/demo folder with examples on how to use this wrapper. The demo directory does not have a package.json or a package lock file, and can be hard to understand and test in external editors such as stackblitz. It also does not include changes done to the angular.json file

It also makes it harder to report issues as seen here:
https://github.com/alvarotrigo/angular-fullpage/issues/59

I have attempted to make a demo for scrolloverflow here: https://stackblitz.com/edit/angular-vqgwxw

However, I can't scroll to see the full text - it jumps to the next section. Any feedback on this would be appreciated.

**Comment by alvarotrigo** [comment]
If you see the README.md file from the demo page you'll see it just uses the package.json from the root folder:

https://github.com/alvarotrigo/angular-fullpage/blob/master/demo/README.md
