### ISSUE TITLE
Possibility to mix fullpage section and normal section

### ISSUE THREAD

**Issue by monsieurPaon** [alvarotrigo/angular-fullpage#69]
Hi, 

Pre-sale question, this is possible to have one section full page and after the first scroll go in a standard html page (without magnetic scroll) ? 

regards,

**Comment by alvarotrigo** [comment]
Short answer: no :)

Long answer: it might be possible if you do certain things, here's a [page doing that](https://www.espasso.com/storefront/test) and here's [the topic where it was mentioned](https://github.com/alvarotrigo/fullPage.js/issues/3205). You'll need `scrollBar:true`.

Also, you can use `scrollOverflow: true`  if you do not mind having a "inner scrolling" within the last section kind of emulating the normal behaviour. See an example [here](https://alvarotrigo.com/fullPage/examples/scrolling.html) applied to all sections.
