### ISSUE TITLE
Any change this can get updated to the latest versions?

### ISSUE THREAD

**Issue by OpticNectar** [alvarotrigo/angular-fullpage#75]
Any chance this plugin can get updated to the latest versions of Angular and Fullpage.js?

**Comment by alvarotrigo** [comment]
Sure! Want to provide some pull requests? That'd be great :)

**Comment by infornite** [comment]
Any update on this?

**Comment by alvarotrigo** [comment]
Not yet.
Want to help to it and perhaps provide a pull request?

**Comment by ivanperesadenko** [comment]
Any updates right now ?

**Comment by alvarotrigo** [comment]
Updated to the latest version of fullPage.js.
For news for Angular, but if any of you is used to work with it, please feel free to provide a  pull request for it. 

What version do you want to update it for btw?
What's the issue with the current one?

**Comment by shwetapurushe** [comment]
Hey @alvarotrigo I'm trying to work on updating it to the latest version on Angular. If I succeed, will submit a PR. 
But when I clone this repo and did `npm install` it fails, node_modules disappears and I cannot proceed. Any ideas?

**Comment by alvarotrigo** [comment]
@shwetapurushe no idea. It seems to be fine on my side.
And [packge.json](https://github.com/alvarotrigo/angular-fullpage/blob/master/package.json) is there too?

**Comment by psalte** [comment]
Suggestion: Update node-gyp as well. That would leave python2 in the dust where it belongs.
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2

**Comment by alvarotrigo** [comment]
Feel free to provide any pull request with the changes.

**Comment by alvarotrigo** [comment]
Fixed in angular-fullpage v0.1.0! 🥳
