### ISSUE TITLE
app.component.html error

### ISSUE THREAD

**Issue by koolkav1** [alvarotrigo/angular-fullpage#76]
"Can't bind to 'options' since it isn't a known property of 'div"

https://github.com/koolkav1/sample-angular-fullpage

It seems to not be correctly imported. I have purchased the full page hobby license for support. I can email you my license key.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [stackblitz](https://stackblitz.com/edit/angular-nqsqwk) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.
