### ISSUE TITLE
Angular fade effect extension issues 

### ISSUE THREAD

**Issue by zeroseisdesign** [alvarotrigo/angular-fullpage#90]
hi, i have added the fade effect to a project in angular. I only need it to be active on the home page, but it is being applied in all other components that have fullscreen added in their .ts.

I've tried to override it where I don't want it to apply with fadeeffect false, but I can't turn it off.

Any idea of how to apply it? Thank you so much

**Comment by alvarotrigo** [comment]
You can try:

```js
fullpage_api.fadingEffect.turnOff();
``` 

Although I would recommend you to just not include the fading effect file in that case or use `fadingEffect: false`.

**Comment by zeroseisdesign** [comment]
Thanks a lot Alvaro, 
It solves my issue just adding this. before your code in each component:
this.fullpage_api.fadingEffect.turnOff();

**Comment by alvarotrigo** [comment]
Awesome to hear! ;)
